### ISSUE TITLE
Should not update titan repository during build time

### ISSUE THREAD

**Issue by BusyJay** [tikv/rust-rocksdb#364]
Source code is expected to be consistent during build time, but `update_titan` features update the submodule to the latest version. It's an abuse of features, which breaks the purpose of versioning.

I suggest to remove the features completely and use make target to update submodules.

/cc @nrc @siddontang

**Comment by nrc** [comment]
Given that there is a make target to do the job, I think there is not much need to have the Cargo feature to do it too, afaict, it doesn't do anything Cargo specific.

>It's an abuse of features, which breaks the purpose of versioning.

If this were a pure Rust project, then I think it is OK to do this rather than adding a script or Makefile, but since there is a Makefile already I think it is better to use it.
